CREATE DATABASE IF NOT EXISTS videoslaravel;
USE videoslaravel;

CREATE TABLE users(
id INT(255) AUTO_INCREMENT NOT NULL,
role VARCHAR(20) NULL,
name VARCHAR(255) NULL,
surname VARCHAR(255) NULL,
email VARCHAR(255) NULL,
password VARCHAR(255) NULL,
image VARCHAR(255) NULL,
created_at DATETIME NULL,
updated_at DATETIME NULL,
remember_token VARCHAR(255) NULL,
CONSTRAINT pk_users PRIMARY KEY(id)
) ENGINE=INNODB;

CREATE TABLE videos(
id INT(255) AUTO_INCREMENT NOT NULL,
user_id INT(255) NOT NULL,
title VARCHAR(255) NULL,
description TEXT NULL,
status VARCHAR(20) NULL,
image VARCHAR(255) NULL,
video_path VARCHAR(255) NULL,
created_at DATETIME NULL,
updated_at DATETIME NULL,
CONSTRAINT pk_videos PRIMARY KEY(id),
CONSTRAINT fk_videos_users FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB;

CREATE TABLE comments(
id INT(255) AUTO_INCREMENT NOT NULL,
user_id INT(255) NOT NULL,
video_id INT(255) NOT NULL,
body TEXT NULL,
created_at DATETIME NULL,
updated_at DATETIME NULL,
CONSTRAINT pk_comments PRIMARY KEY(id),
CONSTRAINT fk_comments_users FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
CONSTRAINT fk_comments_videos FOREIGN KEY(video_id) REFERENCES videos(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB;