CREATE DATABASE IF NOT EXISTS apilaravel CHARACTER SET utf8 COLLATE utf8_general_ci;
USE apilaravel;

CREATE TABLE users(
id INT(255) AUTO_INCREMENT NOT NULL,
role VARCHAR(20) NULL,
name VARCHAR(255) NULL,
surname VARCHAR(255) NULL,
password VARCHAR(255) NULL,
created_at DATETIME NULL,
updated_at DATETIME NULL,
remember_token VARCHAR(255) NULL,
CONSTRAINT pk_users PRIMARY KEY(id)
) ENGINE = INNODB;


CREATE TABLE cars(
id INT(255) AUTO_INCREMENT NOT NULL,
user_id INT(255) NOT NULL,
title VARCHAR(255) NULL,
description TEXT,
price VARCHAR(30) NULL,
status VARCHAR(30) NULL,
created_at DATETIME NULL,
updated_at DATETIME NULL,
remember_token VARCHAR(255) NULL,
CONSTRAINT pk_cars PRIMARY KEY(id),
CONSTRAINT fk_cars_users FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB;
